create database hr_analysis;

show databases;

use hr_analysis;

select*from employees limit 10;

select count(*) from employees;

select attrition,count(*) from employees group by attrition;

# UNDERSTAND THE PROBLEM :
# ==> WHY EMPLOYEES ARE LEAVING.?
#==> WHICH DEPARTMENT IS RISKY ?
#==> WHO IS LIKELY TO LEAVE..?

SELECT ROUND(
SUM(CASE WHEN ATTRITION ='YES' THEN 1 ELSE 0 END)*100.0/COUNT(*),2)
AS ATTRITION_RATE 
FROM EMPLOYEES;

# DEPARTMENT ANALYSIS :

SELECT DEPARTMENT,
COUNT(*) AS TOTAL_EMPLOYEES,
SUM(CASE WHEN ATTRITION ='YES' THEN 1 ELSE 0 END) 
AS ATTRITION_COUNT FROM EMPLOYEES group by DEPARTMENT;

## INSIGHTS: IN RESEARCH & DEVLOPMENT DEPARTMENT HAS HIGH ATTRITION RATE.

# SALARY ANALYSIS.

SELECT 
    CASE 
        WHEN MonthlyIncome < 3000 THEN 'Low Salary'
        WHEN MonthlyIncome BETWEEN 3000 AND 7000 THEN 'Medium Salary'
        ELSE 'High Salary'
    END AS salary_group,
    COUNT(*) AS total,
    SUM(CASE WHEN Attrition='Yes' THEN 1 ELSE 0 END) AS attrition
FROM employees
GROUP BY salary_group;

## INSIGHTS : IN THIS ANALYSIS LOW SALARY PEOPLE LEAVES MORE FROM COMPANY WHICH MEANS WE HAVE TO SEE OUR PACKAGES AND WANTS TO GIVE SOME INCREMENT OR BONUS 
## TO REDUCE ATTRITION.

## AGE ANALYSIS:

SELECT 
    CASE 
        WHEN Age BETWEEN 18 AND 27 THEN '18-27'
        WHEN Age BETWEEN 28 AND 37 THEN '28-37'
        WHEN Age BETWEEN 38 AND 47 THEN '38-47'
        ELSE '48+'
    END AS age_group,
    COUNT(*) AS total,
    SUM(CASE WHEN Attrition='Yes' THEN 1 ELSE 0 END) AS attrition
FROM employees
GROUP BY Age_group;

SELECT Age FROM EMPLOYEES LIMIT 5;

desc employees;

ALTER TABLE employees 
CHANGE COLUMN ï»¿Age Age INT;

## INSIGHTS : IN THE AGE BETWEEN 28-37 HAS HIGH ATTRITION RATE.alter

## JOB ROLE ANALYSIS .
# WHICH JOB ROLE HAS HIGH ATTRITION..?

SELECT 
    JobRole,
    COUNT(*) AS total_employees,
    SUM(CASE WHEN Attrition='Yes' THEN 1 ELSE 0 END) AS attrition_count
FROM employees
GROUP BY JobRole
ORDER BY attrition_count DESC;

# INSIGHTS: IN LABORATORY TECHNICITION,SALES EXECUTIVE,RESERCH SCIENTIST HAS HIGH ATTRITION RATE.

# EXPERIENCE ANALYSIS :
## DO NEW EMPLOYEES LEAVES MORE OR EXPIRENCE ..?

SELECT 
    YearsAtCompany,
    COUNT(*) AS total_employees,
    SUM(CASE WHEN Attrition='Yes' THEN 1 ELSE 0 END) AS attrition_count
FROM employees
GROUP BY YearsAtCompany
ORDER BY YearsAtCompany ;

## INSIGHTS 1-2 YEARS OF EXPERINCE HAS HIGH ATTRITION RATE.

## OVERALL INSIGHTS :

##==> IN RESEARCH & DEVLOPMENT DEPARTMENT HAS HIGH ATTRITION RATE.

#==>  EMPLOYEES IN LOWER SALARY BANDS SHOW HIGHER ATTRITION.

##==> IN THE AGE BETWEEN 28-37 HAS HIGH ATTRITION RATE.

##==> IN LABORATORY TECHNICITION,SALES EXECUTIVE,RESERCH SCIENTIST HAS HIGH ATTRITION RATE.

##==> EMPLOYEES WITH 1-2 YEARS OF EXPERINCE HAS HIGHEST ATTRITION RATE.